apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      proxy:
        upstream: tea
  - path: /coffee
    errorPages:
    - codes: [502]
      return:
        code: 200
        body: "Ops this is embarrassing! We will be back shortly!"
    action:
      proxy:
        upstream: coffee
